### ISSUE TITLE
To the maintainer of this repo

### ISSUE THREAD

**Issue by brupm** [logstash-plugins/logstash-output-influxdb#25]
Hi @electrical I see you brought the repos over. If for some reason you can't maintain and merge-in pull requests let other interested people take over. Both @contentfree and @evgygor have done some great work and it's all currently spread in their forks. 

https://github.com/logstash-plugins/logstash-output-influxdb/pull/23
https://github.com/logstash-plugins/logstash-output-influxdb/pull/15

Thanks

**Comment by brupm** [comment]
@suyograo any love?

**Comment by jordansissel** [comment]
I'm open to merging things. There are currently 8 open pull requests, 6 of which have no comments on them. Someone with infradb experience could review these patches for user safety and quality, and I can merge them.

**Comment by jordansissel** [comment]
@brupm for more detail, the 8 open pull requests are still open because nobody (myself included!) has done the required work for something to be merged. That work is: reviewing the code for problems, testing the code, verifying that new functionality and bug fixes have test coverage that passes, working through any backwards compatibility concerns, discussing any new settings for documentation coverage and meaningful naming, etc.

I can help with some of these things, but as I have no experience with influxdb, I cannot evaluate the correctness of the code nor can I test it adequately.

A brief review of the 8 open PRs, only 1 makes changes to files in the `spec/` directory. This means 7 of them add no tests at all which means they probably aren't ready to be merged yet.

**Comment by brupm** [comment]
Totally understood. Just wanted to make sure the ability would be there should the motivation and follow-thru on these pr's catch up to it. thank you @jordansissel

**Comment by jordansissel** [comment]
Welcome! Basically, if folks test things and agree that backwards compat changes are OK and that the code looks ok, I'm happy to merge. Let me know how I can help :)

**Comment by contentfree** [comment]
Influxdb is going to be releasing a backwards-incompatible version soon (0.9). Most of the commits in my branch are to make this plugin work with 0.9. 

How do we want to go about this transition?

**Comment by chasebolt** [comment]
We really need to get something figured out with this plugin. It does not work with the latest version of Influxdb and PRs are slow to move, if at all. I know people are afraid to merge in changes that may break, but currently this plugin does not even work with the latest Influxdb.

**Comment by suyograo** [comment]
Moved to #34
